"""
提示模板模块

包含各种聊天和工具提示模板
"""

from langchainchat.prompts.chat_prompts import (
    CHAT_PROMPT_TEMPLATE,
    ENHANCED_CHAT_PROMPT_TEMPLATE,
    CONTEXT_PROCESSING_TEMPLATE,
    WORKFLOW_GENERATION_TEMPLATE,
    PROMPT_EXPANSION_TEMPLATE,
    TOOL_CALLING_TEMPLATE,
    ERROR_HANDLING_TEMPLATE
)

__all__ = [
    "CHAT_PROMPT_TEMPLATE",
    "ENHANCED_CHAT_PROMPT_TEMPLATE", 
    "CONTEXT_PROCESSING_TEMPLATE",
    "WORKFLOW_GENERATION_TEMPLATE",
    "PROMPT_EXPANSION_TEMPLATE",
    "TOOL_CALLING_TEMPLATE",
    "ERROR_HANDLING_TEMPLATE"
]
