import asyncio
from typing import TypedDict, List, Dict, Any, Optional, Literal
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage


class GeneratedXmlFile(BaseModel):
    block_id: str = Field(description="The unique ID used in the generated XML <block id='xxx'>.")
    type: str = Field(description="The type of the operation/block.")
    source_description: str = Field(description="The natural language description of the step from parsing.")
    status: Literal["success", "failure"] = Field(description="Status of the XML generation for this block.")
    file_path: Optional[str] = Field(None, description="Full path to the generated .xml file if successful.")
    xml_content: Optional[str] = Field(None, description="The generated XML content. Primarily for debugging or intermediate use.")
    error_message: Optional[str] = Field(None, description="Error message if generation failed.")

class TaskDefinition(BaseModel):
    name: str = Field(description="A concise and descriptive name for the task.")
    type: str = Field(description="The category of the task (e.g., MainTask, GraspTask).")
    details: List[str] = Field(default_factory=list, description="Detailed module steps generated for this task by SAS Step 2, as a list of strings, or other relevant details.")
    sub_tasks: List[str] = Field(default_factory=list, description="A list of names of other tasks that are nested within or executed as part of this task.")
    description: Optional[str] = Field(None, description="A brief natural language description of the task's purpose.")

class RobotFlowAgentState(BaseModel):
    """
    Represents the state of the Robot Flow Agent.
    """
    messages: List[BaseMessage] = Field(default_factory=list, description="The history of messages in the conversation.")
    sse_event_queue: Optional[asyncio.Queue] = Field(default=None, exclude=True, description="SSE event queue for real-time updates from graph nodes.")
    
    # --- 新增: 用于进度事件通信的字段 ---
    current_chat_id: Optional[str] = Field(None, description="Current chat/thread ID for sending progress events via SSE.")
    thread_id: Optional[str] = Field(None, description="Thread ID for LangGraph state management.")
    
    user_input: Optional[str] = Field(None, description="The latest input from the user, consumed after processing by a node.")
    current_user_request: Optional[str] = Field(None, description="The active user request (initialized from first user_input, then revised by feedback) that serves as the basis for the current flow or sub-flow.")

    dialog_state: Optional[Literal[
        # --- Generic States ---
        "initial",                                 # Initial state upon entering the subgraph.
        "error",                                   # A non-recoverable error occurred in a node.
        "generation_failed",                       # A failure happened during an LLM generation step, might be recoverable.
        
        # --- SAS Workflow States (as per simplified diagram) ---
        "user_input_to_task_list",
        "sas_awaiting_task_list_review",
        "task_list_to_module_steps",
        "sas_awaiting_module_steps_review",
        "sas_generating_individual_xmls",
        "sas_individual_xmls_generated_ready_for_mapping",
        "parameter_mapping",
        "sas_step3_completed",
        "merge_xml",
        "sas_merging_completed",
        "final_xml_generated_success",

    ]] = Field("initial", description="The current detailed state of the dialog within the robot flow subgraph.")
    
    clarification_question: Optional[str] = Field(None, description="A question posed to the user for clarification (e.g. about robot model, or ambiguous request).")
    
    config: Dict[str, Any] = Field(default_factory=dict, description="Configuration values, potentially loaded from a file or environment, like API keys, paths, etc.")
    
    # --- Outputs from Step 2 (generate_individual_xmls_node) ---
    generated_node_xmls: Optional[List[GeneratedXmlFile]] = Field(default_factory=list, description="Information about each generated individual XML node file.")
    # --- End of Step 2 outputs ---
    
    # SAS Step 1 outputs
    sas_step1_generated_tasks: Optional[List[TaskDefinition]] = Field(None, description="The structured list of tasks generated from user input by SAS step 1.")
    
    # SAS Step 2 outputs  
    sas_step2_module_steps: Optional[str] = Field(None, description="The specific, executable module steps generated from the process description by SAS step 2.")
    
    # SAS Step 3 outputs
    sas_step3_parameter_mapping: Optional[Dict[str, Dict[str, str]]] = Field(None, description="The mapping from logical parameters to actual parameter file slots, generated by SAS step 3.")
    sas_step3_mapping_report: Optional[str] = Field(None, description="Human-readable report of the parameter mapping process and results from SAS step 3.")

    run_output_directory: Optional[str] = Field(None, description="The directory path for saving outputs for the current run.")

    task_list_accepted: bool = Field(False, description="Flag indicating if the user has accepted the current task list.")
    module_steps_accepted: bool = Field(False, description="Flag indicating if the user has accepted the module steps generated in Step 2.")
    revision_iteration: int = Field(default=0, description="Counter for revision cycles.")

    current_step_description: Optional[str] = Field(None, description="A human-readable description of the current processing step.")
    error_message: Optional[str] = Field(None, description="A message describing an error if one occurred.")
    upload_status: Optional[str] = None # To track file upload status e.g. "success", "remote_address_offline"
    is_error: bool = False

    language: str = Field("zh", description="The language setting for user interactions, e.g., 'zh' or 'en'.")

    completion_status: Optional[Literal["completed_success", "completed_partial", "needs_clarification", "error", "processing"]] = Field(None, description="Indicates how the graph concluded its execution for the current call.")

    merged_xml_file_paths: Optional[List[str]] = Field(default_factory=list, description="Paths to XML files after merging individual task XMLs.")
    
    # Timestamped directory paths to avoid file conflicts
    merged_task_flows_dir: Optional[str] = Field(None, description="Path to the timestamped directory containing merged task XMLs.")
    concatenated_flow_output_dir: Optional[str] = Field(None, description="Path to the timestamped directory containing final concatenated XML.")
    final_flow_xml_path: Optional[str] = Field(None, description="Path to the final concatenated XML file.")
    final_flow_xml_content: Optional[str] = Field(None, description="Content of the final concatenated XML file.")

    class Config:
        arbitrary_types_allowed = True 