version: '3.8'

services:
  backend:
    build: ./backend
    container_name: workflow-editor-backend
    volumes:
      - ./backend:/app
      - ./requirements.txt:/app/requirements.txt
      - ./.env:/app/.env
      - ./global_variables.json:/app/global_variables.json
      - ./flow_editor.db:/app/flow_editor.db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./flow_editor.db
    command: python run_backend.py
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: workflow-editor-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  # 开发环境
  dev:
    image: ubuntu:22.04
    container_name: workflow-editor-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null # 保持容器运行
    depends_on:
      - backend
      - frontend 