version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: workflow-editor-backend
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./flow_editor.db
      - PYTHONPATH=/app
    command: python backend/run_backend.py
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: workflow-editor-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DISABLE_ESLINT_PLUGIN=true
    command: npm start
    depends_on:
      - backend
    restart: unless-stopped

  # 开发环境
  dev:
    image: ubuntu:22.04
    container_name: workflow-editor-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null # 保持容器运行
    depends_on:
      - backend
      - frontend

# 由于不再使用命名卷，可以删除此部分
# volumes:
#   frontend-node-modules:
#     driver: local 