version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/backend.Dockerfile
    container_name: workflow-editor-backend
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-0}
      - DATABASE_URL=sqlite:///database/flow_editor.db
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    command: python backend/run_backend.py
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    build:
      context: ..
      dockerfile: deployment/frontend.Dockerfile
    container_name: workflow-editor-frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

# 使用命名卷来解决不同平台上的node_modules问题
volumes:
  frontend_node_modules: 