"""remove_agent_state_from_flows

Revision ID: 894b09cc159a
Revises: 634f33015b24
Create Date: 2025-06-26 01:22:41.381495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # For JSONB type in downgrade


# revision identifiers, used by Alembic.
revision = '894b09cc159a'
down_revision = '634f33015b24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flows', 'agent_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'flows',
        sa.Column(
            'agent_state', 
            postgresql.JSONB(astext_fallback=True), # Or sa.JSON if you prefer and it matches your original model exactly
            nullable=True, 
            server_default=sa.text("'{}'::jsonb") # Ensure default is correctly cast to jsonb if using JSONB
        )
    )
    # ### end Alembic commands ###
