"""Initial PostgreSQL schema baseline

Revision ID: d116ead34789
Revises: 
Create Date: 2025-04-23 04:27:44.818840

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd116ead34789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('last_updated', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_info_id'), 'version_info', ['id'], unique=False)
    op.create_table('json_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.VECTOR(dim=768), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_json_embeddings_embedding_hnsw',
        'json_embeddings',
        ['embedding_vector'],
        unique=False,
        postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'embedding_vector': 'vector_l2_ops'}
    )
    op.create_index(op.f('ix_json_embeddings_model_name'), 'json_embeddings', ['model_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('last_selected_flow_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('flows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flow_data', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_interacted_chat_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_id'), 'flows', ['id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_data', sa.JSON(), nullable=False),
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('flow_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id', 'key', name='uix_flow_variable')
    )
    op.create_index(op.f('ix_flow_variables_id'), 'flow_variables', ['id'], unique=False)
    op.create_foreign_key(
        'fk_users_last_selected_flow_id',
        'users', 'flows',
        ['last_selected_flow_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_flows_last_interacted_chat_id',
        'flows', 'chats',
        ['last_interacted_chat_id'], ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_flows_last_interacted_chat_id', 'flows', type_='foreignkey')
    op.drop_constraint('fk_users_last_selected_flow_id', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_flow_variables_id'), table_name='flow_variables')
    op.drop_table('flow_variables')
    op.drop_index(op.f('ix_version_info_id'), table_name='version_info')
    op.drop_table('version_info')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_json_embeddings_model_name'), table_name='json_embeddings')
    op.drop_index('ix_json_embeddings_embedding_hnsw', table_name='json_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('json_embeddings')
    op.drop_index(op.f('ix_flows_id'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
